### PR TITLE
Basic styling

### PR DESCRIPTION
**Pull request by lukechesser**
#### Overview

- get some basic styling up
- take the parts of Bootstrap and the Unsplash codebase that we may need

#### Todo

- [x] remove bootstrap as a gem
- [x] import some of the default unsplash stuff
- [x] grab parts of the bootstrap codebase
- [x] install autoprefixer

#### Screenshots/Videos (User Facing Changes)

Login page:

screen shot 2016-06-03 at 6 25 08 pm

Index page:

screen shot 2016-06-03 at 6 24 38 pm

Create a new link:

screen shot 2016-06-03 at 6 24 45 pm

### CODE REVIEW

**Comment by dechuck** [comment]
It's not the right linting. You need to pull master to have the right one.

**Comment by lukechesser** [comment]
@dechuck good to merge? It's probably hard to read but it's mainly CSS

**Comment by dechuck** [comment]
@lukechesser Everything seems good! Can you rebase before? I can do it if you want.

**Comment by dechuck** [comment]
Nice job on the new branding! 😄

**Comment by lukechesser** [comment]
@dechuck oh sorry, didn't see your comment!

**Pull request merged**
